### PR TITLE
Added virtual systems

### PR DESCRIPTION
**Pull request by crcerror**
Added auto-lastplayed >> Lists recent played roms
Added auto-favorites >> Lists as favorites marked roms
Added auto-allgames >> Lists all roms from all system in one list
Added lfl-favorites >> Alternative favorite system read readme.txt for more or visit https://github.com/crcerror/lfl-create

### CODE REVIEW

**Comment by meleu** [comment]
@crcerror IMHO there's no need to have two themes for favorites. Maybe you should submit a separate PR for that lfl-favorites...

**Comment by crcerror** [comment]
@meleu In some usecases I think it can be helpfull.
The big advantage in the favorite system that will be (hopefully) soon installed in the ES system is the easy availability because it's "preinstalled" but *imho* it lacks of flexilibity in the usecase of adding "special" favorites. Maybe a own favorite system for our Mame RoW, or a favourite system for all Tetris version on all systems. With lfl it's much easier to achive more than one fav system with an easy input system - the _User Menu_. *But... you need to get mess around with some scripts*

So I see this the lfl-favorite just as a one system on that the user decides to use it or to use it not... 
About using links via ln... That does not always work on FAT32 systems :(

**Comment by meleu** [comment]
AFAIK that ES branch from @pjft has nothing to do with symbolic links.
But OK, it was just my 2 cents in a hope to see @mattrixk merging this PR.

**Comment by crcerror** [comment]
@meleu Yes I know the ES-branch from @pjft has nothing to do with symbolic links.

Sorry mate, I have to tell you much clearer what I want to explain.
In the Comic Book theme for ex. there are tons of special systems also included. Megaman, CPS1, CPS2... to use this we have to work with symbolic links or via a method like lfl ;) I hope that makes my intention much clearer. If I have done something wrong then please tell me... I'm not very affiliated in using GIT

**Comment by meleu** [comment]
Yeah bro, I got what you mean. I'm just sharing with you good github practices. :-)

The three virtual systems are about to be implemented in ES, and maybe @mattrixk would be interested in merging your logos (or maybe he'll wait what will be done for Carbon and make a grey-scale version as he mentioned in the forums). But the lfl-favorites logo is a trick we use, and maybe he needs more time to decide if he wants to merge it to this repository. That's why I'm suggesting you to submit that in a different PR.

Got it? ;-)

**Comment by pjft** [comment]
I just provided a reply on the forum that hopefully can shed some light on where I see this going:

https://retropie.org.uk/forum/post/89031

Summary: I plan on allowing users to create and manage all those custom game collections within ES, based on unused theme folders, so I'd hope that in... 1-2 months (knock on wood) all our current solutions/workarounds would no longer be needed. 

But first my initial PR needs to be approved :)

Thanks for creating these for IO!

**Comment by crcerror** [comment]
@meleu @pjft Agreed ;)
So I try two pushed ;)

**Pull request closed without merging**
